# Example config file for a crisposon run
#
# Path placeholders are given for reference, but should be 
# replaced with absolute paths to the user's resources
---
  out-dir: "/path/to/work/directory/runs/example_run/out/"
  min-prot-len: 30
  span: 10000
  steps:
    - step:
      type: "seed"
      name: "tnsAB_tniQ"
      e-val: 0.001
      blast-type: "PROT"
      blast-db: "/path/to/work/directory/data/blast_databases/tnsAB_tniQ/blast_db"
    - step:
      type: "filter"
      name: "cas_all"
      e-val: 0.001
      blast-type: "PROT"
      blast-db: "/path/to/work/directory/data/blast_databases/cas_ALL/blast_db"
    - step:
      type: "blast"
      name: "tnsCD"
      e-val: 0.001
      blast-type: "PROT"
      blast-db: "/path/to/work/directory/data/blast_databases/tnsCD/blast_db"
    - step:
      type: "crispr"
      name: null
      e-val: null
      blast-type: null
      blast-db: null